### ISSUE TITLE
Tcl_AsyncDelete: async handler deleted by the wrong thread

### ISSUE THREAD

**Issue by WolfgangFahl** [WolfgangFahl/play-chess-with-a-webcam#34]
Exception ignored in: <function Image.__del__ at 0x7f00f20a46a8>

Traceback (most recent call last):

  File "/opt/python/3.7.1/lib/python3.7/tkinter/__init__.py", line 3507, in __del__

    self.tk.call('image', 'delete', self.name)

RuntimeError: main thread is not in main loop

Exception ignored in: <function Image.__del__ at 0x7f00f20a46a8>

Traceback (most recent call last):

  File "/opt/python/3.7.1/lib/python3.7/tkinter/__init__.py", line 3507, in __del__

    self.tk.call('image', 'delete', self.name)

RuntimeError: main thread is not in main loop

Exception ignored in: <function Image.__del__ at 0x7f00f20a46a8>

Traceback (most recent call last):

  File "/opt/python/3.7.1/lib/python3.7/tkinter/__init__.py", line 3507, in __del__

    self.tk.call('image', 'delete', self.name)

RuntimeError: main thread is not in main loop

Exception ignored in: <function Variable.__del__ at 0x7f00f37556a8>

Traceback (most recent call last):

  File "/opt/python/3.7.1/lib/python3.7/tkinter/__init__.py", line 332, in __del__

    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):

RuntimeError: main thread is not in main loop

Exception ignored in: <function Image.__del__ at 0x7f00f20a46a8>

Traceback (most recent call last):

  File "/opt/python/3.7.1/lib/python3.7/tkinter/__init__.py", line 3507, in __del__

    self.tk.call('image', 'delete', self.name)

RuntimeError: main thread is not in main loop

Exception ignored in: <function Variable.__del__ at 0x7f00f37556a8>

Traceback (most recent call last):

  File "/opt/python/3.7.1/lib/python3.7/tkinter/__init__.py", line 332, in __del__

    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):

RuntimeError: main thread is not in main loop

Exception ignored in: <function Image.__del__ at 0x7f00f20a46a8>

Traceback (most recent call last):

  File "/opt/python/3.7.1/lib/python3.7/tkinter/__init__.py", line 3507, in __del__

    self.tk.call('image', 'delete', self.name)

RuntimeError: main thread is not in main loop

Exception ignored in: <function Image.__del__ at 0x7f00f20a46a8>

Traceback (most recent call last):

  File "/opt/python/3.7.1/lib/python3.7/tkinter/__init__.py", line 3507, in __del__

    self.tk.call('image', 'delete', self.name)

RuntimeError: main thread is not in main loop

Exception ignored in: <function Image.__del__ at 0x7f00f20a46a8>

Traceback (most recent call last):

  File "/opt/python/3.7.1/lib/python3.7/tkinter/__init__.py", line 3507, in __del__

    self.tk.call('image', 'delete', self.name)

RuntimeError: main thread is not in main loop

Exception ignored in: <function Image.__del__ at 0x7f00f20a46a8>

Traceback (most recent call last):

  File "/opt/python/3.7.1/lib/python3.7/tkinter/__init__.py", line 3507, in __del__

    self.tk.call('image', 'delete', self.name)

RuntimeError: main thread is not in main loop

Tcl_AsyncDelete: async handler deleted by the wrong thread

Fatal Python error: Aborted

**Comment by WolfgangFahl** [comment]
https://bugs.python.org/issue39093
